"""empty message

Revision ID: 25caa8dbf0ae
Revises: 18681d3ed2ba
Create Date: 2023-07-16 14:33:51.326397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25caa8dbf0ae'
down_revision = '18681d3ed2ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('degree',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('degree',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
